version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: dron
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "django" ,"-d","dron" ]
      interval: 5s
      retries: 5
      timeout: 5s

  web:
    image: curonny/dron-project:dron-project
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
