# Generated by Django 4.2.4 on 2023-08-18 03:27
import random
import string

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from ..models import Drones
from ..models import Medication

MODELS_LIST = ['Lightweight', 'Middleweight', 'Cruiserweight', 'Heavyweight']
STATES_LIST = ['IDLE', 'Loading', 'Loaded', 'Delivering', 'Delivered', 'Returning']
IMAGES_LIST = ['a.jpg', 'b.jpg', 'c.jpg']


def generate_random_string(length):
    characters = string.ascii_letters + string.digits
    random_string = ''.join(random.choice(characters) for _ in range(length))
    return random_string


def load_data(apps, schema_editor):
    for index, value in enumerate(range(1, 11)):
        Drones.objects.create(serial_number=f'Example {index} ', description=f'Example {index} ',
                              model=random.choice(MODELS_LIST),
                              weight_limit=random.randint(1, 500), battery=random.randint(1, 100),
                              state=random.choice(STATES_LIST))
        Medication.objects.create(name=generate_random_string(10), weight=random.randint(1, 300),
                                  code=f'EXAMPLE_{index}', image=f'medications/{random.choice(IMAGES_LIST)}')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'),
                                                    ('Cruiserweight', 'Cruiserweight'),
                                                    ('Heavyweight', 'Heavyweight')])),
                ('weight_limit', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500),
                                                                         django.core.validators.MinValueValidator(1)])),
                ('battery', models.FloatField(validators=[django.core.validators.MaxValueValidator(100),
                                                          django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('Loading', 'Loading'), ('Loaded', 'Loaded'),
                                                    ('Delivering', 'Delivering'), ('Delivered', 'Delivered'),
                                                    ('Returning', 'Returning')])),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[
                    django.core.validators.RegexValidator(message='This field only contains letters numbers and - _',
                                                          regex='^[a-zA-Z0-9-_]+$')])),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(validators=[django.core.validators.RegexValidator(
                    message='Allowed only upper case letters, underscore and numbers', regex='^[A-Z0-9_]+$')])),
                ('image', models.ImageField(upload_to='medications/')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.drones')),
                ('medications', models.ManyToManyField(to='drones.medication')),
            ],
        ),
        migrations.CreateModel(
            name='DronesBatteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.FloatField(validators=[django.core.validators.MaxValueValidator(100),
                                                          django.core.validators.MinValueValidator(0)])),
                ('drone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.drones')),
            ],
        ),
        migrations.RunPython(load_data),
    ]
