# Generated by Django 4.2.4 on 2023-08-16 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')])),
                ('weight_limit', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('battery', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('Loading', 'Loading'), ('Loaded', 'Loaded'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Returning', 'Returning')])),
            ],
        ),
    ]
