# Generated by Django 4.2.4 on 2023-08-16 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[django.core.validators.RegexValidator(message='This field only contains letters numbers and - _', regex='^[a-zA-Z0-9-_]+$')])),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(validators=[django.core.validators.RegexValidator(message='Allowed only upper case letters, underscore and numbers', regex='^[A-Z0-9_]+$')])),
                ('image', models.ImageField(upload_to='medications/')),
            ],
        ),
    ]
