# Generated by Django 4.2.4 on 2023-08-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.drones')),
                ('medications', models.ManyToManyField(to='drones.medication')),
            ],
        ),
    ]
